### ISSUE TITLE
Check for strong password policy

### ISSUE THREAD

**Issue by sbower** [CU-CloudCollab/aws-config-check#3]
Though users should not use passwords with IAM users we should make sure a sufficiently string policy is in place in case they do use it.

**Comment by paul-e-allen** [comment]
We can point them so this, and/or begin using it as standard with our account setup:

https://github.com/CU-CloudCollab/aws-examples/blob/master/aws-ruby-sdk/iam/set-iam-password-policy.rb

**Comment by sbower** [comment]
yup sounds good.  We should get into the regular account setup.

**Comment by paul-e-allen** [comment]
added password policy check to the script with this commit: https://github.com/CU-CloudCollab/aws-config-check/commit/0d43ffb411d4e2704a607c80d71a3b4b4ca24275

The password policy check uses the parameters suggested in https://github.com/CU-CloudCollab/aws-examples/blob/master/aws-ruby-sdk/iam/set-iam-password-policy.rb, but does not use that code directly.
