### ISSUE TITLE
Overall Status Code

### ISSUE THREAD

**Issue by craig-riecke** [CU-CloudCollab/aws-config-check#7]
At the Vet School, we're going to actually use this script on a Jenkins server to periodically check compliance.  To do this, we need the script to output the standard 0-if-fine, not-0-if-not-fine.

I'm cool with submitting a pull request with the actual changes.  But I wanna make sure that all compliance checks are equal here, and that 0 means no messages are output.  If it needs to be more complicated like:
- Key Rotation Warnings are severity three
- Running the script with --severity=warning will output 1 if a key rotation warning is present, but severity=error will output 0

I just need to know what the levels should be.

**Comment by sbower** [comment]
We have rewritten this to use rpsec and return a pass/fail.  We will be releasing it soon.  Stay tuned.

**Comment by sbower** [comment]
OK We have released the new version here: https://github.com/CU-CloudCollab/cucloud_utils.  We have reworked it to use the cucloud ruby library.  If you are interested in contributing to either fork and PR away!
